// <auto-generated />
using System;
using IdAnimal.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdAnimal.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211084732_AddUserIdToTables")]
    partial class AddUserIdToTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("IdAnimal.Shared.Models.Cattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caravan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GDM")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Caravan");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("Cattle");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.CattleFullImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CattleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CattleId");

                    b.ToTable("CattleFullImages");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.CattleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CattleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descriptors")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keypoints")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CattleId");

                    b.ToTable("CattleImages");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.CattleVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CattleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CattleId");

                    b.ToTable("CattleVideos");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.CustomDataColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CustomDataColumns");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.CustomDataValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CattleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomDataColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CattleId");

                    b.HasIndex("CustomDataColumnId");

                    b.ToTable("CustomDataValues");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.Establishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EstablishmentRegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renspa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.Cattle", b =>
                {
                    b.HasOne("IdAnimal.Shared.Models.Establishment", "Establishment")
                        .WithMany("Cattle")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.CattleFullImage", b =>
                {
                    b.HasOne("IdAnimal.Shared.Models.Cattle", "Cattle")
                        .WithMany("FullImages")
                        .HasForeignKey("CattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cattle");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.CattleImage", b =>
                {
                    b.HasOne("IdAnimal.Shared.Models.Cattle", "Cattle")
                        .WithMany("Images")
                        .HasForeignKey("CattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cattle");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.CattleVideo", b =>
                {
                    b.HasOne("IdAnimal.Shared.Models.Cattle", "Cattle")
                        .WithMany("Videos")
                        .HasForeignKey("CattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cattle");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.CustomDataColumn", b =>
                {
                    b.HasOne("IdAnimal.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.CustomDataValue", b =>
                {
                    b.HasOne("IdAnimal.Shared.Models.Cattle", "Cattle")
                        .WithMany("CustomDataValues")
                        .HasForeignKey("CattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdAnimal.Shared.Models.CustomDataColumn", "CustomDataColumn")
                        .WithMany("Values")
                        .HasForeignKey("CustomDataColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cattle");

                    b.Navigation("CustomDataColumn");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.Establishment", b =>
                {
                    b.HasOne("IdAnimal.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.Cattle", b =>
                {
                    b.Navigation("CustomDataValues");

                    b.Navigation("FullImages");

                    b.Navigation("Images");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.CustomDataColumn", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("IdAnimal.Shared.Models.Establishment", b =>
                {
                    b.Navigation("Cattle");
                });
#pragma warning restore 612, 618
        }
    }
}
